name: IaC Pipeline

on:
  push:
    branches:
    - main

env:
  TERRAFORM_VERSION  : 1.9.6
  ARM_CLIENT_ID      : ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET  : ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID      : ${{ secrets.ARM_TENANT_ID }}

jobs:

  CI-test:
    name: CI Test
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    - run : terraform --version
    - uses: actions/checkout@v4
    - run : terraform -chdir=./terraform/azure init
    - run : terraform -chdir=./terraform/azure validate

  CD-deploy:
    name: CD Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    - uses: actions/checkout@v4
    - run : terraform -chdir=./terraform/azure init
    - run : terraform -chdir=./terraform/azure validate
    - run : terraform -chdir=./terraform/azure plan -out tfplan
    - run : terraform -chdir=./terraform/azure apply tfplan
    - run : terraform -chdir=./terraform/azure show